//
// Copyright (C) 2013-2020 University of Amsterdam
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with this program.  If not, see
// <http://www.gnu.org/licenses/>.
//

import QtQuick		2.11
import JASP.Widgets 1.0
import JASP			1.0

JASPControl
{
	id: jaspControlWithSource

	property var	model				: undefined // model generated by JASPControl
	property var	values				: undefined	// array of string or of label/value pairs
	property var	source				: undefined // reference, or list of references (via name of id) of another control
	property var	sourceModel			: undefined // if the source is unique, it gives the model of this source
	property bool	hasDataFileAsSource	: source === undefined && values === undefined
	property string title
	property alias	label				: jaspControlWithSource.title
	property var	listControl			: undefined // item that holds the values
	property int	count				: listControl ? listControl.count : -1
	property string	optionKey			: "value"
}
